### ISSUE TITLE
Is the data available?

### ISSUE THREAD

**Issue by ericmjl** [brainstorm/cancer-hiveplots#1]
@brainstorm: I was looking through your repo just now, and it looks like the data aren't present there. I think I'm supposed to be looking for a TSV file - but it's not there. Might I be doing something wrong here?

**Comment by brainstorm** [comment]
Hello @ericmjl!

Exciting to have you looking at this project :)

Unfortunately I cannot publish the data right now. On the meantime, you could just simulate sth like:

```
1   1   DEL
1   1   DEL
1   1   BND
1   1   DUP
1   1   DEL
1   1   DEL
1   1   DEL
1   1   INV
1   1   DEL
1   1   BND
```

Optionally changing the numbers in the second column so that inter-chromosomal interactions also show up in one of the quadrants of the plot.

I'll keep you posted since I should release a mock of the data soon for another project anyway ;)

**Comment by ericmjl** [comment]
Okay! I look forward to seeing the mock data coming up. A richer and more realistic mock data would help with the hiveplot plotting examples I've got.

**Comment by brainstorm** [comment]
Hello @ericmjl! I just processed a NA12878-lumpy sample, which gives us a more realistic case for genomic representation of structural variations:

https://github.com/brainstorm/cancer-hiveplots/blob/master/tests/NA12878-svs.csv.gz

I you could please share the resulting plot you get from it, it would be awesome! The way I constructed the three axis on my hiveplot is by having non-`BND` events between two axis (one quadrant?), then `INV`, `DEL`, etc.. events on the other "quadrant", as seen in the [README](https://github.com/brainstorm/cancer-hiveplots/blob/master/README.md).

I'm excited, looking forward to see how it looks like with your library, please share it over here when you have it ready :)

**Comment by brainstorm** [comment]
By the way, just to save you from some data wrangling, I do this with the CSV above:

```
na12878 = pd.read_csv(os.path.join("tests", "NA12878-svs.csv.gz"), dtype=object)
na12878 = na12878[["sample", "chrom1", "chrom2", "svtype"]]
na12878.columns = ["sample", "chrom", "chrom_b", "sv"]
na12878["counts"] = np.nan

hiveplot([(na12878, "NA12878")])
```

Which essentially filters out the positions and gets a table like the one above [in the comment](https://github.com/brainstorm/cancer-hiveplots/issues/1#issuecomment-164549847) about mock data.

**Comment by brainstorm** [comment]
I just uploaded a new mock dataset:

https://raw.githubusercontent.com/brainstorm/cancer-hiveplots/master/tests/all_chroms_1to1.tsv

It should **NOT** look like this (I have to change the chromosomes spacing function in the notebook to show a equally-spaced lines across the axis):

![skarmavbild 2015-12-30 kl 11 48 27](https://cloud.githubusercontent.com/assets/175587/12049745/c1f641e8-aeeb-11e5-9c49-20ca0bffabce.png)
